
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-5pm-2
owner: ucsb-cs156-w24
repo_name: team01-w24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOB2-vOA","is_bot":false,"login":"jonathan-herring","name":"Jonathan Herring"},"headRefName":"Jonathan-Joke-Controller","number":25,"title":"Add Joke Controller and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/25"},{"author":{"id":"U_kgDOB2-vOA","is_bot":false,"login":"jonathan-herring","name":"Jonathan Herring"},"headRefName":"Jonathan-Joke","number":24,"title":"Add Joke Service and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/24"},{"author":{"id":"U_kgDOBdC95g","is_bot":false,"login":"Maria-Saucedo","name":""},"headRefName":"Maria-Tides-Controller","number":23,"title":"Add Tides Controller and Test","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/23"},{"author":{"id":"U_kgDOBtohrg","is_bot":false,"login":"aqiu28517","name":""},"headRefName":"Allen-Location-Controller","number":22,"title":"Add Location Controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/22"},{"author":{"id":"U_kgDOBdC95g","is_bot":false,"login":"Maria-Saucedo","name":""},"headRefName":"Maria-Tides","number":21,"title":"Add Tides Service and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/21"},{"author":{"id":"U_kgDOB2_EDQ","is_bot":false,"login":"jiaqiguan2003","name":""},"headRefName":"Jiaqi-ZipCode-Controller","number":20,"title":"Add ZipCode Controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/20"},{"author":{"id":"U_kgDOB2_EDQ","is_bot":false,"login":"jiaqiguan2003","name":""},"headRefName":"Jiaqi-ZipCode","number":19,"title":"Add ZipCode Service","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/19"},{"author":{"id":"U_kgDOBtohrg","is_bot":false,"login":"aqiu28517","name":""},"headRefName":"Allen-Location","number":18,"title":"Add Location Service","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/18"}]
