
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-5pm-2
owner: ucsb-cs156-w24
repo_name: team01-w24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOBdC95g","is_bot":false,"login":"Maria-Saucedo","name":""},"headRefName":"Maria-HomeController","number":29,"title":"Customize HomeController and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/29"},{"author":{"id":"U_kgDOB2-vOA","is_bot":false,"login":"jonathan-herring","name":"Jonathan Herring"},"headRefName":"Jonathan-READMEFixes","number":28,"title":"Update readme","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/28"},{"author":{"id":"U_kgDOByAtbA","is_bot":false,"login":"livitsimple","name":""},"headRefName":"Olivia-PublicHoliday-Controller","number":27,"title":"Add PublicHoliday Controller and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/27"},{"author":{"id":"U_kgDOBdC95g","is_bot":false,"login":"Maria-Saucedo","name":""},"headRefName":"Maria-Tides-Controller","number":23,"title":"Add Tides Controller and Test","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/23"},{"author":{"id":"U_kgDOBdC95g","is_bot":false,"login":"Maria-Saucedo","name":""},"headRefName":"Maria-Tides","number":21,"title":"Add Tides Service and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/21"}]
