
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-5pm-2
owner: ucsb-cs156-w24
repo_name: team01-w24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOB2-vOA","is_bot":false,"login":"jonathan-herring","name":"Jonathan Herring"},"headRefName":"revert-27-Olivia-PublicHoliday-Controller","number":32,"title":"Revert \"Add PublicHoliday Controller and Tests\"","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/32"},{"author":{"id":"U_kgDOB2-vOA","is_bot":false,"login":"jonathan-herring","name":"Jonathan Herring"},"headRefName":"Jonathan-READMEFixes","number":31,"title":"Update Readme","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/31"},{"author":{"id":"U_kgDOBqdaoA","is_bot":false,"login":"MeronDT","name":""},"headRefName":"Meron-University","number":30,"title":"Add University Service and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-5pm-2/pull/30"}]
